language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpspec run